import streamlit as st
import pandas as pd
from datetime import datetime

# --- 1. Data Loading (Replace this with your actual data source) ---
@st.cache_data
def load_data():
    # I added dummy data here so the app runs. 
    # Replace this with your actual CSV/Database loading logic.
    data = {
        'brand_name': ['Sushi Master', 'Ramen King', 'Matcha Cafe'],
        'investment_usd': [150000, 80000, 50000],
        'franchise_fee_usd': [30000, 15000, 10000],
        'royalty_pct': [5, 6, 4],
        'stores_japan': [120, 85, 40],
        'stores_overseas': [300, 150, 20],
        'target_markets': ['USA, UK, Australia', 'Asia, Europe', 'North America']
    }
    return pd.DataFrame(data)

df = load_data()

# Initialize session state for comparisons
if 'brands_to_compare' not in st.session_state:
    st.session_state.brands_to_compare = []

# --- 2. Your HTML Generator Function ---
def create_comparison_html(compare_df):
    """Create HTML table for download"""
    html = f"""
    <html>
    <head><title>JXPerience - Brand Comparison</title></head>
    <body style="font-family: Arial; padding: 20px;">
        <h1 style="color: #0066cc;">JXPerience - Brand Comparison</h1>
        <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        <h2>Side-by-Side Comparison</h2>
        <table style="border-collapse: collapse; width: 100%; margin-top: 20px;">
            <tr style="background: #0066cc; color: white;">
                <th style="border: 1px solid #ddd; padding: 12px; text-align: left;">Metric</th>
    """
    
    for brand in compare_df['brand_name']:
        html += f'<th style="border: 1px solid #ddd; padding: 12px;">{brand}</th>'
    
    metrics = [
        ('Investment', lambda r: f"${r['investment_usd']}"),
        ('Franchise Fee', lambda r: f"${int(r['franchise_fee_usd']):,}"),
        ('Royalty', lambda r: f"{r['royalty_pct']}%"),
        ('Japan Stores', lambda r: str(r['stores_japan'])),
        ('Overseas', lambda r: str(r['stores_overseas'])),
        ('Target Markets', lambda r: str(r['target_markets'])),
    ]
    
    for metric_name, func in metrics:
        html += f'<tr><td style="border: 1px solid #ddd; padding: 8px;"><b>{metric_name}</b></td>'
        for idx, row in compare_df.iterrows():
            html += f'<td style="border: 1px solid #ddd; padding: 8px;">{func(row)}</td>'
        html += '</tr>'
    
    html += """
        </table>
        <p style="margin-top: 30px; color: #666; font-size: 12px;">
            Generated by JXPerience - Japanese Franchise Overseas Expansion Platform
        </p>
    </body>
    </html>
    """
    return html

# --- 3. The App UI ---
st.title("JXPerience - Franchise Finder")

# Sidebar to let users select brands
st.sidebar.header("Select Brands to Compare")
selected_brands = st.sidebar.multiselect(
    "Choose brands:",
    options=df['brand_name'].tolist(),
    default=st.session_state.brands_to_compare
)
st.session_state.brands_to_compare = selected_brands

num_selected = len(st.session_state.brands_to_compare)

st.write("### Comparison Toolbar")

# ==========================================
# THE FIX: Define the columns BEFORE using them!
# ==========================================
col1, col2 = st.columns(2)

with col1:
    st.info(f"Selected {num_selected} brand(s) for comparison.")

with col2:
    if num_selected >= 2:
        compare_df = df[df['brand_name'].isin(st.session_state.brands_to_compare)]
        html_content = create_comparison_html(compare_df)
        st.download_button(
            label="📄 Download Comparison",
            data=html_content,
            file_name=f"brand_comparison_{datetime.now().strftime('%Y%m%d')}.html",
            mime="text/html",
            use_container_width=True
        )
    else:
        st.warning("Please select at least 2 brands to enable the download.")
