# Remove this line from imports:
# from fpdf import FPDF

# Replace the generate_comparison_pdf function with:
def create_comparison_html(compare_df):
    """Create HTML table for download"""
    html = f"""
    <html>
    <head><title>JXPerience - Brand Comparison</title></head>
    <body style="font-family: Arial; padding: 20px;">
        <h1 style="color: #0066cc;">JXPerience - Brand Comparison</h1>
        <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        <h2>Side-by-Side Comparison</h2>
        <table style="border-collapse: collapse; width: 100%; margin-top: 20px;">
            <tr style="background: #0066cc; color: white;">
                <th style="border: 1px solid #ddd; padding: 12px; text-align: left;">Metric</th>
    """
    
    for brand in compare_df['brand_name']:
        html += f'<th style="border: 1px solid #ddd; padding: 12px;">{brand}</th>'
    
    metrics = [
        ('Investment', lambda r: f"${r['investment_usd']}"),
        ('Franchise Fee', lambda r: f"${int(r['franchise_fee_usd']):,}"),
        ('Royalty', lambda r: f"{r['royalty_pct']}%"),
        ('Japan Stores', lambda r: str(r['stores_japan'])),
        ('Overseas', lambda r: str(r['stores_overseas'])),
        ('Target Markets', lambda r: str(r['target_markets'])),
    ]
    
    for metric_name, func in metrics:
        html += f'<tr><td style="border: 1px solid #ddd; padding: 8px;"><b>{metric_name}</b></td>'
        for idx, row in compare_df.iterrows():
            html += f'<td style="border: 1px solid #ddd; padding: 8px;">{func(row)}</td>'
        html += '</tr>'
    
    html += """
        </table>
        <p style="margin-top: 30px; color: #666; font-size: 12px;">
            Generated by JXPerience - Japanese Franchise Overseas Expansion Platform
        </p>
    </body>
    </html>
    """
    return html

# Then in the comparison toolbar section, replace the PDF download button with:
with col2:
    if num_selected >= 2:
        compare_df = df[df['brand_name'].isin(st.session_state.brands_to_compare)]
        html_content = create_comparison_html(compare_df)
        st.download_button(
            label="📄 Download Comparison",
            data=html_content,
            file_name=f"brand_comparison_{datetime.now().strftime('%Y%m%d')}.html",
            mime="text/html",
            use_container_width=True
        )
